-- Módulo de CARTERA (CAR): persistencia del nivel de la fila, del saldo por tercero y de
-- la clave canónica del tercero en el balance.
--
-- Enteramente ADITIVA: agrega columnas anulables (o con valor por defecto), una tabla nueva
-- vacía y dos índices. No modifica ni borra ningún dato existente, y los demás módulos
-- (Inventarios, Activos Fijos, Ingresos, CxP, Nómina) quedan exactamente como estaban:
-- todas las columnas nuevas son null para ellos, salvo `imputable`, cuyo default `true`
-- reproduce el comportamiento actual (todo el detalle promovido suma).
--
-- Contexto de las decisiones, para quien lea esto dentro de un año:
--
--  · `nivel` + `imputable` en el detalle, en vez de dos tablas. Cinco de los catorce
--    formatos reales de clientes traen el tercero y sus documentos EN EL MISMO archivo;
--    partirlos en dos almacenes obligaría a duplicar borrador, versiones, anexos,
--    eliminación y exportación. Con una sola tabla, la cabecera del tercero se guarda sin
--    imputar y sirve de control contra la suma de sus documentos.
--
--  · `cartera_saldo_tercero` es un DERIVADO reconstruible del detalle, no una segunda
--    fuente. Existe por rendimiento (un archivo de SAP trae 26.279 filas y 4.424 terceros;
--    el cruce no puede reagregarlas abriendo el JSON en cada render) y porque permite
--    comparar por NIT dos archivos del mismo período con un JOIN.
--
--  · `clave_tercero` en el balance por tercero convive con `nit_tercero`, que se seguirá
--    escribiendo. `nit_tercero` guarda el núcleo de 9 dígitos, y truncar ahí fusiona
--    cédulas de 10 que solo difieren en el último dígito —en un archivo real hay 1.917—,
--    juntando personas distintas en un mismo renglón de la conciliación. La clave nueva
--    conserva el documento completo y solo retira el dígito de verificación cuando lo es.

-- ===== 1. Encabezado del cargue: qué nivel imputa, a qué fecha y con qué edades =====
ALTER TABLE "modulo_dato_encabezado"
  ADD COLUMN IF NOT EXISTS "nivel_saldo"  TEXT,
  ADD COLUMN IF NOT EXISTS "fecha_corte"  DATE,
  ADD COLUMN IF NOT EXISTS "rangos_edades" JSONB,
  ADD COLUMN IF NOT EXISTS "trm_cierre"   DECIMAL(12,4);

-- ===== 2. Detalle: qué es cada fila, si suma, y de qué tercero y cuenta es =====
ALTER TABLE "modulo_dato_detalle"
  ADD COLUMN IF NOT EXISTS "nivel"          TEXT,
  ADD COLUMN IF NOT EXISTS "imputable"      BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "nit_canonico"   TEXT,
  ADD COLUMN IF NOT EXISTS "cuenta_cliente" TEXT,
  ADD COLUMN IF NOT EXISTS "origen_cartera" TEXT;

-- El cruce por tercero filtra por (cargue, NIT); sin el índice recorrería el detalle entero.
CREATE INDEX IF NOT EXISTS "modulo_dato_detalle_encabezado_nit_idx"
  ON "modulo_dato_detalle"("encabezado_id", "nit_canonico");

-- ===== 3. Saldo por tercero (derivado del detalle) =====
CREATE TABLE IF NOT EXISTS "cartera_saldo_tercero" (
    "id"              INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "encabezado_id"   INTEGER NOT NULL,
    "lote_id"         TEXT NOT NULL,
    "nivel"           TEXT NOT NULL,
    "origen"          TEXT NOT NULL,
    "cuenta_cliente"  TEXT NOT NULL DEFAULT '',
    "origen_cartera"  TEXT NOT NULL DEFAULT '',
    "clave_tercero"   TEXT NOT NULL,
    "nit_original"    TEXT,
    "dv"              TEXT,
    "sucursal"        TEXT,
    "nombre"          TEXT,
    "saldo"           DECIMAL(18,2) NOT NULL DEFAULT 0,
    "saldo_reportado" DECIMAL(18,2),
    "suma_edades"     DECIMAL(18,2),
    "edades"          JSONB,
    "documentos"      INTEGER NOT NULL DEFAULT 0,
    "dias_max"        INTEGER,
    "creado_en"       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cartera_saldo_tercero_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "cartera_saldo_tercero_encabezado_id_fkey"
      FOREIGN KEY ("encabezado_id") REFERENCES "modulo_dato_encabezado"("id")
      ON DELETE CASCADE ON UPDATE CASCADE
);

-- Un tercero aparece UNA vez por (cargue, archivo, nivel, origen, cuenta, nacional/exterior).
-- `origen` entra en la llave a propósito: el mismo tercero del mismo archivo puede tener a
-- la vez su saldo declarado por la cabecera y el agregado de sus documentos, y compararlos
-- es justamente el control.
CREATE UNIQUE INDEX IF NOT EXISTS "cartera_saldo_tercero_unico"
  ON "cartera_saldo_tercero"("encabezado_id", "lote_id", "nivel", "origen", "cuenta_cliente", "origen_cartera", "clave_tercero");

CREATE INDEX IF NOT EXISTS "cartera_saldo_tercero_clave_idx"
  ON "cartera_saldo_tercero"("encabezado_id", "clave_tercero");

-- ===== 4. Clave canónica del tercero en el balance por tercero =====
-- Queda en null hasta que el backfill (`scripts/backfill-clave-tercero.ts`) la calcule
-- para los cargues existentes; de ahí en adelante la escribe la captura.
ALTER TABLE "balance_tercero_detalle"
  ADD COLUMN IF NOT EXISTS "clave_tercero" TEXT;

CREATE INDEX IF NOT EXISTS "balance_tercero_detalle_encabezado_clave_idx"
  ON "balance_tercero_detalle"("encabezado_id", "clave_tercero");
