-- Reportes internos: el usuario autenticado crea la novedad, Xentria gestiona
-- el estado y se pueden adjuntar capturas. El portal publico se conserva.

ALTER TABLE "tickets_soporte"
  ADD COLUMN IF NOT EXISTS "creado_por_id" INTEGER;

CREATE INDEX IF NOT EXISTS "tickets_soporte_creado_por_id_creado_en_idx"
  ON "tickets_soporte"("creado_por_id", "creado_en");

ALTER TABLE "tickets_soporte"
  DROP CONSTRAINT IF EXISTS "tickets_soporte_estado_check";

ALTER TABLE "tickets_soporte"
  DROP CONSTRAINT IF EXISTS "tickets_soporte_resolucion_check";

ALTER TABLE "tickets_soporte"
  ADD CONSTRAINT "tickets_soporte_estado_check"
  CHECK ("estado" IN ('abierto', 'en_proceso', 'resuelto', 'cerrado'));

ALTER TABLE "tickets_soporte"
  ADD CONSTRAINT "tickets_soporte_resolucion_check"
  CHECK (
    ("estado" IN ('abierto', 'en_proceso', 'cerrado'))
    OR
    ("estado" = 'resuelto' AND "solucion" IS NOT NULL AND "resuelto_en" IS NOT NULL)
  );

CREATE TABLE IF NOT EXISTS "adjuntos_ticket_soporte" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ticket_id" INTEGER NOT NULL,
    "clave_objeto" TEXT NOT NULL,
    "nombre_archivo" TEXT NOT NULL,
    "tipo_contenido" TEXT NOT NULL,
    "tamano_bytes" INTEGER NOT NULL,
    "creado_en" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "adjuntos_ticket_soporte_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "adjuntos_ticket_soporte_ticket_id_fkey"
      FOREIGN KEY ("ticket_id") REFERENCES "tickets_soporte"("id")
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "adjuntos_ticket_soporte_clave_objeto_key"
  ON "adjuntos_ticket_soporte"("clave_objeto");

CREATE INDEX IF NOT EXISTS "adjuntos_ticket_soporte_ticket_id_idx"
  ON "adjuntos_ticket_soporte"("ticket_id");

UPDATE "modulos_plataforma"
SET
  "etiqueta" = 'Reportes',
  "descripcion" = 'Novedades reportadas por los usuarios para que Xentria las gestione.',
  "grupo" = 'Trabajo',
  "icono" = 'msg',
  "orden" = 55,
  "habilitado_no_administradores" = true,
  "bloqueable_no_administradores" = false,
  "actualizado_en" = CURRENT_TIMESTAMP
WHERE "clave" = 'soporte';

INSERT INTO "permisos"
  ("codigo", "modulo", "accion", "etiqueta", "descripcion", "activo", "creado_en")
VALUES
  (
    'soporte:ver',
    'soporte',
    'ver',
    'Ver reportes',
    'Consultar las novedades propias y su estado de gestión.',
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'soporte:crear',
    'soporte',
    'crear',
    'Crear reporte',
    'Montar una novedad con descripción e imágenes para que Xentria la gestione.',
    true,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("codigo") DO UPDATE SET
  "modulo" = EXCLUDED."modulo",
  "accion" = EXCLUDED."accion",
  "etiqueta" = EXCLUDED."etiqueta",
  "descripcion" = EXCLUDED."descripcion",
  "activo" = true;

UPDATE "permisos"
SET
  "etiqueta" = 'Administrar reportes',
  "descripcion" = 'Consultar todas las novedades, cambiar su estado y documentar la solución.'
WHERE "codigo" = 'soporte:administrar';

INSERT INTO "roles_permisos" ("rol_id", "permiso_id", "creado_en")
SELECT rol."id", permiso."id", CURRENT_TIMESTAMP
FROM "roles" AS rol
CROSS JOIN "permisos" AS permiso
WHERE rol."codigo" IN ('Socio', 'Gerente', 'Senior', 'Staff', 'Administrador', 'Superadministrador')
  AND permiso."codigo" IN ('soporte:ver', 'soporte:crear')
ON CONFLICT ("rol_id", "permiso_id") DO NOTHING;
