-- Cuentas NO MODULARES del cruce contable.
--
-- Una fila del cruce agrega TODAS las cuentas del cliente homologadas a una cuenta
-- Russell de 4 dígitos. Algunas de esas cuentas no hacen parte de la conciliación del
-- módulo (p. ej. «AJUSTE INVENTARIO», «INVENTARIO EN TRÁNSITO»): su saldo aparecía como
-- diferencia sin serlo, y el analista solo podía explicarlo con una marca, no restarlo.
--
-- La exclusión cuelga de la MARCA (FK dura en cascada, igual que los soportes): sin
-- marca no hay exclusión —la nota de la marca es su justificación— y retirar la marca
-- retira las exclusiones. Vive por período, como la marca.
--
-- `valor_al_marcar` es constancia de lo que valía la cuenta cuando se excluyó; lo que
-- se resta de «Contabilidad» al calcular la diferencia ajustada es el valor ACTUAL de la
-- cuenta en el balance emparejado, para que ambos lados se muevan juntos.

CREATE TABLE IF NOT EXISTS "cuenta_no_modular_cruce" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "marca_id" INTEGER NOT NULL,
    "cuenta_8" TEXT NOT NULL,
    "nombre_cuenta" TEXT NOT NULL,
    "valor_al_marcar" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "creado_en" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cuenta_no_modular_cruce_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "cuenta_no_modular_cruce_marca_id_fkey"
      FOREIGN KEY ("marca_id") REFERENCES "marca_cruce_modulo"("id")
      ON DELETE CASCADE ON UPDATE CASCADE
);

-- Una cuenta no se excluye dos veces en la misma marca.
CREATE UNIQUE INDEX IF NOT EXISTS "cuenta_no_modular_cruce_unica"
  ON "cuenta_no_modular_cruce"("marca_id", "cuenta_8");

CREATE INDEX IF NOT EXISTS "cuenta_no_modular_cruce_marca_id_idx"
  ON "cuenta_no_modular_cruce"("marca_id");
