-- Superadministración: catálogo de módulos funcionales publicables para
-- usuarios no administrativos. La autorización granular sigue en RBAC.

CREATE TABLE "modulos_plataforma" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "clave" TEXT NOT NULL,
    "etiqueta" TEXT NOT NULL,
    "descripcion" TEXT,
    "grupo" TEXT NOT NULL,
    "icono" TEXT NOT NULL,
    "orden" INTEGER NOT NULL DEFAULT 0,
    "habilitado_no_administradores" BOOLEAN NOT NULL DEFAULT true,
    "bloqueable_no_administradores" BOOLEAN NOT NULL DEFAULT true,
    "creado_en" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actualizado_en" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "modulos_plataforma_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "modulos_plataforma_clave_key" ON "modulos_plataforma"("clave");
CREATE INDEX "modulos_plataforma_grupo_orden_idx" ON "modulos_plataforma"("grupo", "orden");

INSERT INTO "modulos_plataforma"
  ("clave", "etiqueta", "descripcion", "grupo", "icono", "orden", "habilitado_no_administradores", "bloqueable_no_administradores")
VALUES
  ('dashboard', 'Inicio', 'Resumen operativo de la plataforma.', 'Trabajo', 'home', 10, true, false),
  ('balance', 'Balance de comprobación', 'Carga, versionamiento y consulta del balance por cliente.', 'Trabajo', 'doc', 20, true, true),
  ('mapeo', 'Mapeo plan estándar', 'Parametrización de cuentas contra el plan estándar Russell.', 'Trabajo', 'settings', 30, true, true),
  ('razonabilidad', 'Razonabilidad', 'Análisis de razonabilidad y hallazgos.', 'Trabajo', 'ai', 40, true, true),
  ('conciliaciones', 'Conciliaciones', 'Cruces entre contabilidad y módulos auxiliares.', 'Trabajo', 'play', 50, true, true),
  ('dian', 'Impuestos DIAN', 'Cruce de declaraciones contra contabilidad.', 'Trabajo', 'doc', 60, true, true),
  ('requerimientos', 'Requerimientos', 'Plantillas, generación y seguimiento de solicitudes de información.', 'Trabajo', 'folder', 70, true, true),
  ('presentaciones', 'Presentaciones', 'Informes ejecutivos para cliente.', 'Trabajo', 'chart', 80, true, true),
  ('calendario', 'Calendario', 'Vencimientos y eventos de clientes.', 'Trabajo', 'calendar', 90, true, true),
  ('auditoria', 'Auditoría', 'Registro de actividad del sistema.', 'Configuración', 'log', 100, true, true),
  ('clientes', 'Clientes', 'Administración de clientes y parámetros de negocio.', 'Configuración', 'users', 110, true, true),
  ('equipos', 'Equipos y carteras', 'Equipos de trabajo, integrantes y cartera asignada.', 'Configuración', 'users', 120, true, true),
  ('mapeos_dian', 'Mapeos DIAN', 'Parametrización de cuentas para formularios DIAN.', 'Configuración', 'doc', 130, true, true),
  ('usuarios', 'Usuarios', 'Administración de cuentas de usuario.', 'Configuración', 'users', 140, true, true),
  ('modulos', 'Módulos y campos', 'Campos estándar por módulo de conciliación.', 'Configuración', 'box', 150, true, true),
  ('roles', 'Permisos por rol', 'Matriz de permisos por cargo.', 'Configuración', 'settings', 160, true, true),
  ('publicacion_modulos', 'Publicación de módulos', 'Control de visibilidad para usuarios no administrativos.', 'Configuración', 'eye', 170, true, true);

INSERT INTO "roles"
  ("codigo", "nombre", "descripcion", "rango", "es_operativo", "es_sistema", "activo", "creado_en", "actualizado_en")
VALUES
  (
    'Superadministrador',
    'Superadministrador',
    'Controla la publicación visual de módulos y conserva acceso completo a la administración de la plataforma.',
    6,
    false,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("codigo") DO UPDATE SET
  "nombre" = EXCLUDED."nombre",
  "descripcion" = EXCLUDED."descripcion",
  "rango" = EXCLUDED."rango",
  "es_sistema" = true,
  "activo" = true,
  "actualizado_en" = CURRENT_TIMESTAMP;

INSERT INTO "permisos"
  ("codigo", "modulo", "accion", "etiqueta", "descripcion", "activo", "creado_en")
VALUES
  ('publicacion_modulos:ver', 'publicacion_modulos', 'ver', 'Ver publicación de módulos', 'Consultar qué módulos están publicados para usuarios no administrativos.', true, CURRENT_TIMESTAMP),
  ('publicacion_modulos:configurar', 'publicacion_modulos', 'configurar', 'Configurar publicación de módulos', 'Habilitar u ocultar módulos para usuarios no administrativos.', true, CURRENT_TIMESTAMP)
ON CONFLICT ("codigo") DO UPDATE SET
  "modulo" = EXCLUDED."modulo",
  "accion" = EXCLUDED."accion",
  "etiqueta" = EXCLUDED."etiqueta",
  "descripcion" = EXCLUDED."descripcion",
  "activo" = true;

-- El Superadministrador hereda todos los permisos existentes.
INSERT INTO "roles_permisos" ("rol_id", "permiso_id")
SELECT r."id", p."id"
FROM "roles" r
CROSS JOIN "permisos" p
WHERE r."codigo" = 'Superadministrador'
ON CONFLICT ("rol_id", "permiso_id") DO NOTHING;
