-- Marcas de auditoría del cruce contable.
--
-- La antigua «justificación» de una diferencia pasa a ser una MARCA numerada: la cédula
-- (la tabla del cruce) solo lleva la marca ①②③ y el detalle vive al pie, en observaciones,
-- con referencia al anexo y soportes adjuntos.
--
-- Se RENOMBRA la tabla en vez de recrearla para conservar las justificaciones ya escritas:
-- cada una queda convertida en marca, numerada por período según su orden de creación.

ALTER TABLE "justificacion_cruce_modulo" RENAME TO "marca_cruce_modulo";

ALTER TABLE "marca_cruce_modulo" RENAME COLUMN "justificado_por" TO "marcado_por";
ALTER TABLE "marca_cruce_modulo" RENAME COLUMN "justificado_por_id" TO "marcado_por_id";
ALTER TABLE "marca_cruce_modulo" RENAME COLUMN "justificado_en" TO "marcado_en";

ALTER TABLE "marca_cruce_modulo" ADD COLUMN IF NOT EXISTS "referencia_anexo" TEXT;
ALTER TABLE "marca_cruce_modulo" ADD COLUMN IF NOT EXISTS "numero" INTEGER;

-- Numeración retroactiva: dentro de cada (cliente, módulo, período), por antigüedad.
UPDATE "marca_cruce_modulo" AS m
SET "numero" = orden."fila"
FROM (
  SELECT
    "id",
    ROW_NUMBER() OVER (
      PARTITION BY "cliente_id", "modulo_codigo", "periodo"
      ORDER BY "marcado_en", "id"
    ) AS "fila"
  FROM "marca_cruce_modulo"
) AS orden
WHERE m."id" = orden."id";

ALTER TABLE "marca_cruce_modulo" ALTER COLUMN "numero" SET NOT NULL;

ALTER INDEX IF EXISTS "justificacion_cruce_modulo_pkey" RENAME TO "marca_cruce_modulo_pkey";
ALTER INDEX IF EXISTS "justificacion_cruce_modulo_unica" RENAME TO "marca_cruce_modulo_unica";
ALTER INDEX IF EXISTS "justificacion_cruce_modulo_periodo_idx" RENAME TO "marca_cruce_modulo_periodo_idx";

-- El número tampoco se repite dentro del período (la app lo asigna como max+1).
CREATE UNIQUE INDEX IF NOT EXISTS "marca_cruce_modulo_numero_unico"
  ON "marca_cruce_modulo" ("cliente_id", "modulo_codigo", "periodo", "numero");

-- Soportes de la marca (el anexo digital). El binario vive en el almacenamiento de
-- objetos; aquí solo la clave. FK dura: retirar la marca se lleva sus soportes.
CREATE TABLE IF NOT EXISTS "adjuntos_marca_cruce" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "marca_id" INTEGER NOT NULL,
    "clave_objeto" TEXT NOT NULL,
    "nombre_archivo" TEXT NOT NULL,
    "tipo_contenido" TEXT NOT NULL,
    "tamano_bytes" INTEGER NOT NULL,
    "subido_por_id" INTEGER,
    "creado_en" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "adjuntos_marca_cruce_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "adjuntos_marca_cruce_marca_id_fkey"
      FOREIGN KEY ("marca_id") REFERENCES "marca_cruce_modulo"("id")
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "adjuntos_marca_cruce_clave_objeto_key"
  ON "adjuntos_marca_cruce"("clave_objeto");

CREATE INDEX IF NOT EXISTS "adjuntos_marca_cruce_marca_id_idx"
  ON "adjuntos_marca_cruce"("marca_id");
