-- Mesa de ayuda: reporte publico con enlace privado de seguimiento y bandeja
-- autenticada para que Administrador/Superadministrador documenten la solucion.

CREATE TABLE "tickets_soporte" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "codigo" TEXT NOT NULL,
    "nombre_reportante" TEXT NOT NULL,
    "apellido_reportante" TEXT NOT NULL,
    "asunto" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'abierto',
    "solucion" TEXT,
    "resuelto_por_id" INTEGER,
    "resuelto_por_nombre" TEXT,
    "resuelto_en" TIMESTAMP(3) WITH TIME ZONE,
    "token_acceso_hash" TEXT NOT NULL,
    "creado_en" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actualizado_en" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tickets_soporte_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tickets_soporte_estado_check" CHECK ("estado" IN ('abierto', 'resuelto')),
    CONSTRAINT "tickets_soporte_resolucion_check" CHECK (
      ("estado" = 'abierto' AND "solucion" IS NULL AND "resuelto_en" IS NULL)
      OR
      ("estado" = 'resuelto' AND "solucion" IS NOT NULL AND "resuelto_en" IS NOT NULL)
    )
);

CREATE UNIQUE INDEX "tickets_soporte_codigo_key" ON "tickets_soporte"("codigo");
CREATE UNIQUE INDEX "tickets_soporte_token_acceso_hash_key" ON "tickets_soporte"("token_acceso_hash");
CREATE INDEX "tickets_soporte_estado_creado_en_idx" ON "tickets_soporte"("estado", "creado_en");

INSERT INTO "modulos_plataforma"
  ("clave", "etiqueta", "descripcion", "grupo", "icono", "orden", "habilitado_no_administradores", "bloqueable_no_administradores")
VALUES
  ('soporte', 'Tickets de soporte', 'Bandeja interna para consultar solicitudes y documentar su solucion.', 'Configuración', 'bell', 230, false, false)
ON CONFLICT ("clave") DO UPDATE SET
  "etiqueta" = EXCLUDED."etiqueta",
  "descripcion" = EXCLUDED."descripcion",
  "grupo" = EXCLUDED."grupo",
  "icono" = EXCLUDED."icono",
  "orden" = EXCLUDED."orden",
  "habilitado_no_administradores" = EXCLUDED."habilitado_no_administradores",
  "bloqueable_no_administradores" = EXCLUDED."bloqueable_no_administradores",
  "actualizado_en" = CURRENT_TIMESTAMP;

INSERT INTO "permisos"
  ("codigo", "modulo", "accion", "etiqueta", "descripcion", "activo", "creado_en")
VALUES
  (
    'soporte:administrar',
    'soporte',
    'administrar',
    'Administrar tickets de soporte',
    'Consultar las solicitudes publicas y documentar la solucion visible para el reportante.',
    true,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("codigo") DO UPDATE SET
  "modulo" = EXCLUDED."modulo",
  "accion" = EXCLUDED."accion",
  "etiqueta" = EXCLUDED."etiqueta",
  "descripcion" = EXCLUDED."descripcion",
  "activo" = true;

INSERT INTO "roles_permisos" ("rol_id", "permiso_id", "creado_en")
SELECT rol."id", permiso."id", CURRENT_TIMESTAMP
FROM "roles" AS rol
CROSS JOIN "permisos" AS permiso
WHERE rol."codigo" IN ('Administrador', 'Superadministrador')
  AND permiso."codigo" = 'soporte:administrar'
ON CONFLICT ("rol_id", "permiso_id") DO NOTHING;
